ykey = 'tNVSPxTZuK97fliYWToZrZpCGASCD0HlyF7s554dF_IdGdO1vAenbda05dWc6zUrsvXPE25NpvVJw1ZhohHYp-4n68rsIzrDPQAwh0lceNXGdjprDYMTAvHM_oMvXnYx' 
gkey = 'AIzaSyCu1ZA_-wimdbPaUssBz2Y3IjJQ_3FEaGU'
api_url = 'https://api.yelp.com'
search_path = '/v3/businesses/search'
business_path = '/v3/businesses/'